name: train-ttm.yaml
on:
  push:
    branches:
      - master

jobs:
  pipeline:
    container:
      image: quay.io/aicoe/ocp-ci-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - env:
          ACTION: 1
          AWS_ACCESS_KEY_ID: ${{ github.event.client_payload.AWS_ACCESS_KEY_ID  ||
            secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.client_payload.AWS_SECRET_ACCESS_KEY
            || secrets.AWS_SECRET_ACCESS_KEY }}
          CEPH_BUCKET: ${{ github.event.client_payload.S3_BUCKET || secrets.S3_BUCKET
            }}
          CEPH_BUCKET_PREFIX: ${{ github.event.client_payload.PREFIX|| secrets.CEPH_BUCKET_PREFIX
            }}
          CEPH_KEY_ID: ${{ github.event.client_payload.AWS_ACCESS_KEY_ID  || secrets.AWS_ACCESS_KEY_ID
            }}
          CEPH_SECRET_KEY: ${{ github.event.client_payload.AWS_SECRET_ACCESS_KEY ||
            secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          GITHUB_ORG: ${{ github.event.client_payload.ORG || secrets.ORG }}
          GITHUB_REPO: ${{ github.event.client_payload.REPO || secrets.REPO }}
          MODE: 1
          REMOTE: 1
          S3_BUCKET: ${{ github.event.client_payload.S3_BUCKET || secrets.S3_BUCKET
            }}
          S3_ENDPOINT_URL: ${{ github.event.client_payload.S3_ENDPOINT_URL || secrets.S3_ENDPOINT_URL
            }}
        name: Run Model Training
        uses: redhat-et/time-to-merge-tool@v1
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
